# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c47772d5c53f57e4855a09afab54c779276902d78cfab14b545f2d21cf3076d16cad715f9ada89ec5ea4775e01a2d4dd44b038340e8dcf773e5d52ed82ee6034

test:
  secret_key_base: fb2fe5b37bfc6d8ffdb8d0277c7cc40194439ee8a6d314d069a49ef8920f5332a5aea511d53b6f66869a75f8b27c54e3b3ac84c51262dfaa1e1f78909d694ea0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
